name: coco_fiscal
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  http: ^0.13.6
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  table_calendar: ^3.0.9
  carousel_slider: ^4.2.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
  assets:
    - assets/fonts/
    - assets/images/


